### PR TITLE
Re-engineered solution with many new features

### PR DESCRIPTION
**Pull request by noelmcloughlin**
This PR is a rewrite to introduce many new features. Resolves#14, #40, #45, #47, #50.  Existing pillars for MongoDB 3.0 upwards should work fine; support for older/broken releases is dropped.    

**VERIFICATION**
Tested on  Centos7. Ubuntu 16.04, and MacOS using `use_repo: True` and `use_archives: True`

**Logs**
[centos_firewalld_selinuxEnforcing.log](https://github.com/saltstack-formulas/mongodb-formula/files/2492199/centos_firewalld_selinuxEnforcing.log)
[macos.log](https://github.com/saltstack-formulas/mongodb-formula/files/2492200/macos.log)
[ubuntu.log](https://github.com/saltstack-formulas/mongodb-formula/files/2492201/ubuntu.log)

**CHANGELOG**

**New features added**
    - MongoDB connector for BI (mongosql daemon)
    - remove / clean states
    - create user and group
    - new pillar data structure (keep backwards compatibility)
    - MacOS tarball
    - Linux tarball
    - mongosqld service
    - /etc/mongorc.js file
    - systemd
    - transparent_hugepages disabling support
    - firewalld services
    - updated README and pillar.example
    - selinux enforcing handling

**deprecated stuff**
    - 'mongodb.logrotate': see 'mongodb.server.config' state.
    - 'mongodb.tools'    : see 'mongodb.server.config' state.

**removed**
    - state 'mongodb.mongos': see 'mongodb.server.config' state
    - mongodb/files/mongos.upstart.conf.jinja (unused)
    - mongos.conf.jinja (see service.conf.jinja)

*** Not done ***
- Make selinux and firewalld business logic conditional on grains instead of pillars.

### CODE REVIEW

**Comment by noelmcloughlin** [comment]
According to online dictionaries both words have same meaning?
> deprecate 
> another term for depreciate (sense 2).
> "he deprecates the value of children's television"

**Comment by javierbertoli** [comment]
> According to online dictionaries both words have same meaning?
> 
> > deprecate
> > another term for depreciate (sense 2).
> > "he deprecates the value of children's television"

Huh... you're right, didn't know they are synonyms in English. Never saw it used as `depreciated` in computing, always as `deprecated` (that's why I mentioned it), and in my language (Spanish) they have different meaning. Oh, well, ignore my comment :smile:

**Comment by noelmcloughlin** [comment]
No problem, I was not sure myself.

 Its fair comment to say `deprecated` is more common in Computing. I updated the commit. thanks

**Comment by noelmcloughlin** [comment]
Thanks @gtmanfred good luck with the change!!

**Comment by noelmcloughlin** [comment]
@nmadhok @thatch45  OpenSDS will be supporting MongoDB in their Bali release. 

Since this repo is unmaintained, I would be grateful if either of you could review the PR.

The PR is heavily tested.

The repo has not been updated since 2016 so this PR will be improvement, and I will follow up on any technical debt.

**Comment by noelmcloughlin** [comment]
Thanks @aboe76 and @nmadhok Appreciated.

**Pull request merged**
