### PR TITLE
Adds jessie support.

### PR DESCRIPTION
**Pull request by toopy**

### CODE REVIEW

**Comment by nmadhok** [comment]
@toopy Please add distro specfic things to map.jinja

**Comment by gravyboat** [comment]
@babilen Is that you saying we should close this PR? If so, @toopy can you think of any use case this resolves that wouldn't be addressed as babilen has said?

**Comment by babilen** [comment]
@gravyboat It certainly isn't necessary for installing redis on jessie. There might be some value in offering ways to configure their third-party repository to allow users to get access to newer releases, but I think that I would prefer if that could be handled in an explicit state and not unconditionally in `redis/init.sls`

**Comment by toopy** [comment]
I won't use this formula for now. Then I can't work on it more and maintain
the wheezy case.

You can close and I will make better if needed later.

Thank you for your feed back. Sorry if I reply so lately.
Le 26 mars 2015 07:56, "Wolodja Wentland" <notifications@github.com> a
écrit :

**Comment by nmadhok** [comment]
Thanks @toopy! Hoping for a pull request from you in future!

**Pull request closed without merging**
