### PR TITLE
Split mongod and mongos, removed mongodb meta state

### PR DESCRIPTION
**Pull request by sethcenterbar**
references #56 

So.. this is my first stab at it, attempting to follow your comments. I know it's not the most perfect solution, but it was the quickest way to separate them. I'm wondering if it would be best to leave the mongodb metastate as the installation of the server, and then have mongod and mongos simply configure and turn on those services. Thoughts @noelmcloughlin?

### CODE REVIEW

**Comment by noelmcloughlin** [comment]
It depends. One approach suggests `mongodb` and `mongodb.clean` metastate should handle everything (mongos, mongod, bi, roto3t) but the modularity you are introducing allows pick & choose. That is certainly consistent and perhaps solution of least surprise (a good thing).

The other approach suggests `mongodb` and `mongodb.clean` metastate handle the most common use case - namely `mongod` - on the premise that newbies/busy people get what they expected and nothing else

I would lean towards 1st option - the README is there for a reason.

I'll do some testing during the week. thanks.

**Comment by sethcenterbar** [comment]
Ok. You'll find in my pull request that I opted for there to be no mongodb.init, and assumed the user would just include the metastates they wanted. So, basically neither of the two things you just said 😆 Oops!

**Comment by noelmcloughlin** [comment]
No problem - If we want a `mongodb.init` it can be added as afterthought. 
Don't forget to update the README.
I'll test next week and review the PR. thx

**Comment by noelmcloughlin** [comment]
Hi @sethcenterbar 

I got some time to check the PR now - there are some issues.  Here are a few suggestions.

1.  In `mongodb/mongod` directory change all occurrences of `mongodb server` to `mongodb mongod`.
2. In `mongodb/mongos` directory change all occurrences of `mongodb server` to `mongodb mongos`.
3.  You could safely delete all directories named `depreciated` I think.
4. Fix `mongod/init.sls`  i.e. change `server` to `mongod`
5. Fix `mongos/init.sls` i.e. change `server` to `mongos`.
6. Maybe  `defaults.yaml` should be tidied up similarly.  The `mongodb.server` stuff could be moved to `mongodb.system` since "server" is defunct.   something like this ...
```
mongodb:
  system:
     ... no change here .. etc  ...
    package: mongodb-org      ##<<< mongodb.server.stuff moved here.
    version: 4.0
    use_repo: False
    use_archive: False
    use_schema: False
    disable_transparent_hugepages: true
    binpath: /usr
    user: mongodb
    group: mongodb
```

**Comment by sethcenterbar** [comment]
@noelmcloughlin , I really want to be able to help with this. I'm going to take some time to learn kitchen and try to understand the testing process better so I don't have to bounce every attempt off of you.

**Comment by noelmcloughlin** [comment]
I don't mind, learning kitchen is not necessary since you can just do testing in a local VM. This is your first stab at Salt so bounce off me all you want.  There is saltstack community on Slack too where you can get advice. We're open!!

**Comment by noelmcloughlin** [comment]
Hi @sethcenterbar 
Did you get any further with this?  I have two other PRs to get merged before/after yours.

**Comment by sethcenterbar** [comment]
I haven’t made any progress. Go ahead 🙃

**Comment by noelmcloughlin** [comment]
It would be great to get this tested. The improvements in this PR are needed imho.

**Comment by noelmcloughlin** [comment]
replaced by https://github.com/saltstack-formulas/mongodb-formula/pull/83

**Pull request closed without merging**
